<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Untitled Document</title>
<style type="text/css">
<!--
.TRAFFIC {	color: #000;
}
.style10 {font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 12px; }
.style14 {color: #FFFFFF}
.style15 {color: #FFFFFF; font-size: 10px; }
.style17 {font-size: 16px; color: #0000FF; font-family: Verdana, Arial, Helvetica, sans-serif;}
-->
</style>
</head>

<body>
<div align="center">
  <table width="762" height="27">
    <tr>
      <td width="752"><img src="pictures/contact-us.jpg" width="753" height="41" /></td>
    </tr>
    <tr>
      <td><table width="751" height="22" border="0" align="center" background="blue.PNG">
        <tr bgcolor="#9999CC">
          <td width="111" height="18" bgcolor="#000099"><div align="center" class="style10"><a href="home.php" class="style14">HOME</a></div></td>
          <td width="199" bgcolor="#000099"><div align="center" class="style10"><a href="manage.php" class="style14">TRAFFIC MANAGEMENT</a></div></td>
          <td width="145" bgcolor="#000099"><div align="center" class="style10"><a href="data.php" class="style14">TRAFFIC DATA</a></div></td>
          <td width="121" bgcolor="#000099"><div align="center">
              <div align="center" class="style10"><a href="road.php" class="style14">TRAFFIC ROAD</a></div>
          </div></td>
          <td width="145" bgcolor="#000099"><div align="center" class="style10"><a href="service.php" class="style14">CONTACT</a></div></td>
        </tr>
      </table></td>
    </tr>
    <tr>
      <td><div align="center">
        <table width="747" height="523" border="0" align="center" bgcolor="#FFFF99">
            <form id="form1" name="form1" method="post" action="noond.php">

              <tr bgcolor="#FFFF99">
                <td height="53" colspan="3" align="center" bordercolor="#FF00FF"><div align="center" class="style15">
                    <h4 class="style17">Morning Duties</h4>
                </div></td>
              </tr>
              <tr>
                <td width="124" height="24">FIRST NAME </td>
                <td colspan="2"><label>
                  <input name="fname" type="text" id="fname" />
                  </label>          </td>
              </tr>
              <tr>
                <td height="41">SECOND NAME </td>
                <td colspan="2"><label>
                  <input name="sname" type="text" id="sname" />
                  </label>          </td>
              </tr>
              <tr>
                <td height="48">ADDRESS</td>
                <td colspan="2"><label>
                  <input name="address" type="text" id="address" />
                  </label>          </td>
              </tr>
              <tr>
                <td height="39">TELEPHONE</td>
                <td colspan="2"><label>
                  <input name="telephone" type="text" id="telephone" />
                  </label>          </td>
              </tr>
              <tr>
                <td height="49">DATE</td>
                <td colspan="2"><input name="date" type="text" id="date" /></td>
              </tr>
              <tr>
                <td height="54">TIME IN </td>
                <td colspan="2"><label>
                  <input name="timein" type="text" id="timein" />
                  </label>          </td>
              </tr>
              <tr>
                <td height="28">TIME OUT </td>
                <td colspan="2"><label>
                  <input name="timeout" type="text" id="timeout" />
                  </label>          </td>
              </tr>
              <tr>
                <td height="30">&nbsp;</td>
                <td width="343"><label>
                  <input type="submit" name="Submit" value="Submit" />
                  </label>          </td>
                <td width="266"><div align="center">
                    <input type="reset" name="Submit2" value="Reset" />
                </div></td>
              </tr>
              <tr bgcolor="#FF00FF">
                <td><a href="personel.php"><img src="pictures/btnPrevious.png" width="109" height="56" border="0" /></a></td>
                <td colspan="2"><div align="right"><a href="evening.php"><img src="pictures/btnNext.png" width="120" height="58" border="0" /></a></div></td>
              </tr>
            </form>
        </table>
      </div></td>
    </tr>
  </table>
</div>
</body>
</html>
